// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: STGProto.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace STG {

  /// <summary>Holder for reflection information generated from STGProto.proto</summary>
  public static partial class STGProtoReflection {

    #region Descriptor
    /// <summary>File descriptor for STGProto.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static STGProtoReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5TVEdQcm90by5wcm90bxIDc3RnIqcCCglHYW1lYm9hcmQSDgoGc2l6ZV94",
            "GAEgASgFEg4KBnNpemVfeRgCIAEoBRIOCgZzaXplX3oYAyABKAUSDAoEdGlj",
            "axgEIAEoBRIhCglnYW1lc3RhdGUYBSABKA4yDi5zdGcuR2FtZXN0YXRlEiwK",
            "B2dsb2JhbHMYBiADKAsyGy5zdGcuR2FtZWJvYXJkLkdsb2JhbHNFbnRyeRIk",
            "CgNtYXAYByADKAsyFy5zdGcuR2FtZWJvYXJkLk1hcEVudHJ5Gi4KDEdsb2Jh",
            "bHNFbnRyeRILCgNrZXkYASABKAUSDQoFdmFsdWUYAiABKAg6AjgBGjUKCE1h",
            "cEVudHJ5EgsKA2tleRgBIAEoBRIYCgV2YWx1ZRgCIAEoCzIJLnN0Zy5DZWxs",
            "OgI4ASK2AgoEQ2VsbBIdCgd0ZXJyYWluGAEgASgLMgwuc3RnLkVsZW1lbnQS",
            "IQoLYWx0X3RlcnJhaW4YAiABKAsyDC5zdGcuRWxlbWVudBImChB0ZXJyYWlu",
            "X21vZGlmaWVyGAMgASgLMgwuc3RnLkVsZW1lbnQSHAoGcGlja3VwGAQgASgL",
            "Mgwuc3RnLkVsZW1lbnQSGQoDbW9iGAUgASgLMgwuc3RnLkVsZW1lbnQSGQoD",
            "dG9wGAYgASgLMgwuc3RnLkVsZW1lbnQSGwoFbm9ydGgYByABKAsyDC5zdGcu",
            "RWxlbWVudBIaCgRlYXN0GAggASgLMgwuc3RnLkVsZW1lbnQSGwoFc291dGgY",
            "CSABKAsyDC5zdGcuRWxlbWVudBIaCgR3ZXN0GAogASgLMgwuc3RnLkVsZW1l",
            "bnQi/AEKB0VsZW1lbnQSFwoCaWQYASABKA4yCy5zdGcuRWxlbUlkEgwKBHJ1",
            "bGUYAiABKAUSGQoFY29sb3IYAyABKA4yCi5zdGcuQ29sb3ISDwoHY2hhbm5l",
            "bBgEIAEoBRIbCgNkaXIYBSABKA4yDi5zdGcuRGlyZWN0aW9uEg0KBWNvdW50",
            "GAYgASgFEh8KCWludmVudG9yeRgHIAMoCzIMLnN0Zy5FbGVtZW50EiQKBHRh",
            "Z3MYCCADKAsyFi5zdGcuRWxlbWVudC5UYWdzRW50cnkaKwoJVGFnc0VudHJ5",
            "EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoBToCOAEiWwoFSW5wdXQSHwoH",
            "cHJpbWFyeRgBIAEoDjIOLnN0Zy5EaXJlY3Rpb24SIQoJc2Vjb25kYXJ5GAIg",
            "ASgOMg4uc3RnLkRpcmVjdGlvbhIOCgZhY3Rpb24YAyABKAUqkwMKBkVsZW1J",
            "ZBIVChFFTEVNRU5UX1VOREVGSU5FRBAAEgkKBVNQQUNFEAESCQoFRkxPT1IQ",
            "AhIICgRXQUxMEAMSCAoERVhJVBAEEgkKBVdBVEVSEAUSCAoERklSRRAGEggK",
            "BERJUlQQBxIKCgZHUkFWRUwQCBIHCgNJQ0UQCRIJCgVGT1JDRRAKEgoKBkNM",
            "T05FUhALEggKBEhJTlQQDBIOCgpDSEVDS1BPSU5UEA0SCQoFUEFORUwQZBIK",
            "CgZDT1JORVIQZRILCgZCVVRUT04QyAESCQoERE9PUhDJARILCgZTT0NLRVQQ",
            "ygESCgoFVEhJRUYQywESDQoIVEVMRVBPUlQQzAESCQoEVFJBUBDNARILCgZU",
            "T0dHTEUQ9QMSCgoFUE9QVVAQ9gMSCQoEQ0hJUBCsAhIICgNLRVkQrQISCQoE",
            "SVRFTRCuAhIJCgRCT01CEK8CEgsKBlBMQVlFUhCQAxIKCgVCTE9DSxCRAxIM",
            "CgdNT05TVEVSEJIDEgkKBFRBTksQkwMSCwoGQ0FOT1BZEPQDKkEKCUdhbWVz",
            "dGF0ZRIXChNHQU1FU1RBVEVfVU5ERUZJTkVEEAASCAoEUExBWRABEggKBExP",
            "U0UQAhIHCgNXSU4QAyp0CgVDb2xvchITCg9DT0xPUl9VTkRFRklORUQQABIH",
            "CgNSRUQQARIICgRCTFVFEAISCQoFR1JFRU4QAxIKCgZZRUxMT1cQBBIICgRD",
            "WUFOEAUSCwoHTUFHRU5UQRAGEgoKBk9SQU5HRRAHEgkKBUJST1dOEAgqbAoJ",
            "RGlyZWN0aW9uEhcKE0RJUkVDVElPTl9VTkRFRklORUQQABIFCgFOEAESBQoB",
            "RRACEgUKAVMQAxIFCgFXEAQSBgoCTkUQBRIGCgJTRRAGEgYKAlNXEAcSBgoC",
            "TlcQCBIKCgZSQU5ET00QCUIGqgIDU1RHYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::STG.ElemId), typeof(global::STG.Gamestate), typeof(global::STG.Color), typeof(global::STG.Direction), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::STG.Gameboard), global::STG.Gameboard.Parser, new[]{ "SizeX", "SizeY", "SizeZ", "Tick", "Gamestate", "Globals", "Map" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::STG.Cell), global::STG.Cell.Parser, new[]{ "Terrain", "AltTerrain", "TerrainModifier", "Pickup", "Mob", "Top", "North", "East", "South", "West" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::STG.Element), global::STG.Element.Parser, new[]{ "Id", "Rule", "Color", "Channel", "Dir", "Count", "Inventory", "Tags" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { null, }),
            new pbr::GeneratedClrTypeInfo(typeof(global::STG.Input), global::STG.Input.Parser, new[]{ "Primary", "Secondary", "Action" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum ElemId {
    [pbr::OriginalName("ELEMENT_UNDEFINED")] ElementUndefined = 0,
    /// <summary>
    /// TERRAIN
    /// </summary>
    [pbr::OriginalName("SPACE")] Space = 1,
    [pbr::OriginalName("FLOOR")] Floor = 2,
    /// <summary>
    /// APPEARING, INVISIBLE, BLUE 
    /// </summary>
    [pbr::OriginalName("WALL")] Wall = 3,
    [pbr::OriginalName("EXIT")] Exit = 4,
    [pbr::OriginalName("WATER")] Water = 5,
    [pbr::OriginalName("FIRE")] Fire = 6,
    [pbr::OriginalName("DIRT")] Dirt = 7,
    [pbr::OriginalName("GRAVEL")] Gravel = 8,
    [pbr::OriginalName("ICE")] Ice = 9,
    [pbr::OriginalName("FORCE")] Force = 10,
    [pbr::OriginalName("CLONER")] Cloner = 11,
    [pbr::OriginalName("HINT")] Hint = 12,
    [pbr::OriginalName("CHECKPOINT")] Checkpoint = 13,
    /// <summary>
    /// NESW
    /// </summary>
    [pbr::OriginalName("PANEL")] Panel = 100,
    [pbr::OriginalName("CORNER")] Corner = 101,
    /// <summary>
    /// TERRAIN_MODIFIER
    /// </summary>
    [pbr::OriginalName("BUTTON")] Button = 200,
    [pbr::OriginalName("DOOR")] Door = 201,
    [pbr::OriginalName("SOCKET")] Socket = 202,
    /// <summary>
    /// KEY, ITEM
    /// </summary>
    [pbr::OriginalName("THIEF")] Thief = 203,
    [pbr::OriginalName("TELEPORT")] Teleport = 204,
    [pbr::OriginalName("TRAP")] Trap = 205,
    /// <summary>
    /// Toggles between terrain layers. GFX should allow hotkey for viewing the alternate layer.
    /// </summary>
    [pbr::OriginalName("TOGGLE")] Toggle = 501,
    /// <summary>
    /// Exposes the terrain layers. GFX should allow hotkey for viewing the alternate layer.
    /// </summary>
    [pbr::OriginalName("POPUP")] Popup = 502,
    /// <summary>
    /// PICKUP
    /// </summary>
    [pbr::OriginalName("CHIP")] Chip = 300,
    /// <summary>
    /// SINGLE_USE, FOREVER_USE
    /// </summary>
    [pbr::OriginalName("KEY")] Key = 301,
    /// <summary>
    ///FLIPPER, FIREBOOTS, SKATES, SUCTIONBOOTS
    /// </summary>
    [pbr::OriginalName("ITEM")] Item = 302,
    [pbr::OriginalName("BOMB")] Bomb = 303,
    /// <summary>
    /// MOB
    /// </summary>
    [pbr::OriginalName("PLAYER")] Player = 400,
    [pbr::OriginalName("BLOCK")] Block = 401,
    [pbr::OriginalName("MONSTER")] Monster = 402,
    [pbr::OriginalName("TANK")] Tank = 403,
    /// <summary>
    /// TOP
    /// </summary>
    [pbr::OriginalName("CANOPY")] Canopy = 500,
  }

  public enum Gamestate {
    [pbr::OriginalName("GAMESTATE_UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("PLAY")] Play = 1,
    [pbr::OriginalName("LOSE")] Lose = 2,
    [pbr::OriginalName("WIN")] Win = 3,
  }

  public enum Color {
    [pbr::OriginalName("COLOR_UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("RED")] Red = 1,
    [pbr::OriginalName("BLUE")] Blue = 2,
    [pbr::OriginalName("GREEN")] Green = 3,
    [pbr::OriginalName("YELLOW")] Yellow = 4,
    [pbr::OriginalName("CYAN")] Cyan = 5,
    [pbr::OriginalName("MAGENTA")] Magenta = 6,
    [pbr::OriginalName("ORANGE")] Orange = 7,
    [pbr::OriginalName("BROWN")] Brown = 8,
  }

  public enum Direction {
    [pbr::OriginalName("DIRECTION_UNDEFINED")] Undefined = 0,
    [pbr::OriginalName("N")] N = 1,
    [pbr::OriginalName("E")] E = 2,
    [pbr::OriginalName("S")] S = 3,
    [pbr::OriginalName("W")] W = 4,
    [pbr::OriginalName("NE")] Ne = 5,
    [pbr::OriginalName("SE")] Se = 6,
    [pbr::OriginalName("SW")] Sw = 7,
    [pbr::OriginalName("NW")] Nw = 8,
    [pbr::OriginalName("RANDOM")] Random = 9,
  }

  #endregion

  #region Messages
  public sealed partial class Gameboard : pb::IMessage<Gameboard>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Gameboard> _parser = new pb::MessageParser<Gameboard>(() => new Gameboard());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Gameboard> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STG.STGProtoReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Gameboard() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Gameboard(Gameboard other) : this() {
      sizeX_ = other.sizeX_;
      sizeY_ = other.sizeY_;
      sizeZ_ = other.sizeZ_;
      tick_ = other.tick_;
      gamestate_ = other.gamestate_;
      globals_ = other.globals_.Clone();
      map_ = other.map_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Gameboard Clone() {
      return new Gameboard(this);
    }

    /// <summary>Field number for the "size_x" field.</summary>
    public const int SizeXFieldNumber = 1;
    private int sizeX_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SizeX {
      get { return sizeX_; }
      set {
        sizeX_ = value;
      }
    }

    /// <summary>Field number for the "size_y" field.</summary>
    public const int SizeYFieldNumber = 2;
    private int sizeY_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SizeY {
      get { return sizeY_; }
      set {
        sizeY_ = value;
      }
    }

    /// <summary>Field number for the "size_z" field.</summary>
    public const int SizeZFieldNumber = 3;
    private int sizeZ_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SizeZ {
      get { return sizeZ_; }
      set {
        sizeZ_ = value;
      }
    }

    /// <summary>Field number for the "tick" field.</summary>
    public const int TickFieldNumber = 4;
    private int tick_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Tick {
      get { return tick_; }
      set {
        tick_ = value;
      }
    }

    /// <summary>Field number for the "gamestate" field.</summary>
    public const int GamestateFieldNumber = 5;
    private global::STG.Gamestate gamestate_ = global::STG.Gamestate.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Gamestate Gamestate {
      get { return gamestate_; }
      set {
        gamestate_ = value;
      }
    }

    /// <summary>Field number for the "globals" field.</summary>
    public const int GlobalsFieldNumber = 6;
    private static readonly pbc::MapField<int, bool>.Codec _map_globals_codec
        = new pbc::MapField<int, bool>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForBool(16, false), 50);
    private readonly pbc::MapField<int, bool> globals_ = new pbc::MapField<int, bool>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, bool> Globals {
      get { return globals_; }
    }

    /// <summary>Field number for the "map" field.</summary>
    public const int MapFieldNumber = 7;
    private static readonly pbc::MapField<int, global::STG.Cell>.Codec _map_map_codec
        = new pbc::MapField<int, global::STG.Cell>.Codec(pb::FieldCodec.ForInt32(8, 0), pb::FieldCodec.ForMessage(18, global::STG.Cell.Parser), 58);
    private readonly pbc::MapField<int, global::STG.Cell> map_ = new pbc::MapField<int, global::STG.Cell>();
    /// <summary>
    /// p = z * (size_x + size_y) + y * size_x + x
    /// x = (p % size_z) % size_x
    /// y = (p % size_z) // size_x
    /// z = p // size_z
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<int, global::STG.Cell> Map {
      get { return map_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Gameboard);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Gameboard other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SizeX != other.SizeX) return false;
      if (SizeY != other.SizeY) return false;
      if (SizeZ != other.SizeZ) return false;
      if (Tick != other.Tick) return false;
      if (Gamestate != other.Gamestate) return false;
      if (!Globals.Equals(other.Globals)) return false;
      if (!Map.Equals(other.Map)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SizeX != 0) hash ^= SizeX.GetHashCode();
      if (SizeY != 0) hash ^= SizeY.GetHashCode();
      if (SizeZ != 0) hash ^= SizeZ.GetHashCode();
      if (Tick != 0) hash ^= Tick.GetHashCode();
      if (Gamestate != global::STG.Gamestate.Undefined) hash ^= Gamestate.GetHashCode();
      hash ^= Globals.GetHashCode();
      hash ^= Map.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SizeX != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SizeX);
      }
      if (SizeY != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SizeY);
      }
      if (SizeZ != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SizeZ);
      }
      if (Tick != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Tick);
      }
      if (Gamestate != global::STG.Gamestate.Undefined) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Gamestate);
      }
      globals_.WriteTo(output, _map_globals_codec);
      map_.WriteTo(output, _map_map_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SizeX != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SizeX);
      }
      if (SizeY != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(SizeY);
      }
      if (SizeZ != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(SizeZ);
      }
      if (Tick != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Tick);
      }
      if (Gamestate != global::STG.Gamestate.Undefined) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Gamestate);
      }
      globals_.WriteTo(ref output, _map_globals_codec);
      map_.WriteTo(ref output, _map_map_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SizeX != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SizeX);
      }
      if (SizeY != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SizeY);
      }
      if (SizeZ != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SizeZ);
      }
      if (Tick != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Tick);
      }
      if (Gamestate != global::STG.Gamestate.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gamestate);
      }
      size += globals_.CalculateSize(_map_globals_codec);
      size += map_.CalculateSize(_map_map_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Gameboard other) {
      if (other == null) {
        return;
      }
      if (other.SizeX != 0) {
        SizeX = other.SizeX;
      }
      if (other.SizeY != 0) {
        SizeY = other.SizeY;
      }
      if (other.SizeZ != 0) {
        SizeZ = other.SizeZ;
      }
      if (other.Tick != 0) {
        Tick = other.Tick;
      }
      if (other.Gamestate != global::STG.Gamestate.Undefined) {
        Gamestate = other.Gamestate;
      }
      globals_.Add(other.globals_);
      map_.Add(other.map_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SizeX = input.ReadInt32();
            break;
          }
          case 16: {
            SizeY = input.ReadInt32();
            break;
          }
          case 24: {
            SizeZ = input.ReadInt32();
            break;
          }
          case 32: {
            Tick = input.ReadInt32();
            break;
          }
          case 40: {
            Gamestate = (global::STG.Gamestate) input.ReadEnum();
            break;
          }
          case 50: {
            globals_.AddEntriesFrom(input, _map_globals_codec);
            break;
          }
          case 58: {
            map_.AddEntriesFrom(input, _map_map_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SizeX = input.ReadInt32();
            break;
          }
          case 16: {
            SizeY = input.ReadInt32();
            break;
          }
          case 24: {
            SizeZ = input.ReadInt32();
            break;
          }
          case 32: {
            Tick = input.ReadInt32();
            break;
          }
          case 40: {
            Gamestate = (global::STG.Gamestate) input.ReadEnum();
            break;
          }
          case 50: {
            globals_.AddEntriesFrom(ref input, _map_globals_codec);
            break;
          }
          case 58: {
            map_.AddEntriesFrom(ref input, _map_map_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Cell : pb::IMessage<Cell>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Cell> _parser = new pb::MessageParser<Cell>(() => new Cell());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Cell> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STG.STGProtoReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cell() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cell(Cell other) : this() {
      terrain_ = other.terrain_ != null ? other.terrain_.Clone() : null;
      altTerrain_ = other.altTerrain_ != null ? other.altTerrain_.Clone() : null;
      terrainModifier_ = other.terrainModifier_ != null ? other.terrainModifier_.Clone() : null;
      pickup_ = other.pickup_ != null ? other.pickup_.Clone() : null;
      mob_ = other.mob_ != null ? other.mob_.Clone() : null;
      top_ = other.top_ != null ? other.top_.Clone() : null;
      north_ = other.north_ != null ? other.north_.Clone() : null;
      east_ = other.east_ != null ? other.east_.Clone() : null;
      south_ = other.south_ != null ? other.south_.Clone() : null;
      west_ = other.west_ != null ? other.west_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Cell Clone() {
      return new Cell(this);
    }

    /// <summary>Field number for the "terrain" field.</summary>
    public const int TerrainFieldNumber = 1;
    private global::STG.Element terrain_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element Terrain {
      get { return terrain_; }
      set {
        terrain_ = value;
      }
    }

    /// <summary>Field number for the "alt_terrain" field.</summary>
    public const int AltTerrainFieldNumber = 2;
    private global::STG.Element altTerrain_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element AltTerrain {
      get { return altTerrain_; }
      set {
        altTerrain_ = value;
      }
    }

    /// <summary>Field number for the "terrain_modifier" field.</summary>
    public const int TerrainModifierFieldNumber = 3;
    private global::STG.Element terrainModifier_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element TerrainModifier {
      get { return terrainModifier_; }
      set {
        terrainModifier_ = value;
      }
    }

    /// <summary>Field number for the "pickup" field.</summary>
    public const int PickupFieldNumber = 4;
    private global::STG.Element pickup_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element Pickup {
      get { return pickup_; }
      set {
        pickup_ = value;
      }
    }

    /// <summary>Field number for the "mob" field.</summary>
    public const int MobFieldNumber = 5;
    private global::STG.Element mob_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element Mob {
      get { return mob_; }
      set {
        mob_ = value;
      }
    }

    /// <summary>Field number for the "top" field.</summary>
    public const int TopFieldNumber = 6;
    private global::STG.Element top_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element Top {
      get { return top_; }
      set {
        top_ = value;
      }
    }

    /// <summary>Field number for the "north" field.</summary>
    public const int NorthFieldNumber = 7;
    private global::STG.Element north_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element North {
      get { return north_; }
      set {
        north_ = value;
      }
    }

    /// <summary>Field number for the "east" field.</summary>
    public const int EastFieldNumber = 8;
    private global::STG.Element east_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element East {
      get { return east_; }
      set {
        east_ = value;
      }
    }

    /// <summary>Field number for the "south" field.</summary>
    public const int SouthFieldNumber = 9;
    private global::STG.Element south_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element South {
      get { return south_; }
      set {
        south_ = value;
      }
    }

    /// <summary>Field number for the "west" field.</summary>
    public const int WestFieldNumber = 10;
    private global::STG.Element west_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Element West {
      get { return west_; }
      set {
        west_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Cell);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Cell other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Terrain, other.Terrain)) return false;
      if (!object.Equals(AltTerrain, other.AltTerrain)) return false;
      if (!object.Equals(TerrainModifier, other.TerrainModifier)) return false;
      if (!object.Equals(Pickup, other.Pickup)) return false;
      if (!object.Equals(Mob, other.Mob)) return false;
      if (!object.Equals(Top, other.Top)) return false;
      if (!object.Equals(North, other.North)) return false;
      if (!object.Equals(East, other.East)) return false;
      if (!object.Equals(South, other.South)) return false;
      if (!object.Equals(West, other.West)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (terrain_ != null) hash ^= Terrain.GetHashCode();
      if (altTerrain_ != null) hash ^= AltTerrain.GetHashCode();
      if (terrainModifier_ != null) hash ^= TerrainModifier.GetHashCode();
      if (pickup_ != null) hash ^= Pickup.GetHashCode();
      if (mob_ != null) hash ^= Mob.GetHashCode();
      if (top_ != null) hash ^= Top.GetHashCode();
      if (north_ != null) hash ^= North.GetHashCode();
      if (east_ != null) hash ^= East.GetHashCode();
      if (south_ != null) hash ^= South.GetHashCode();
      if (west_ != null) hash ^= West.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (terrain_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Terrain);
      }
      if (altTerrain_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AltTerrain);
      }
      if (terrainModifier_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TerrainModifier);
      }
      if (pickup_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Pickup);
      }
      if (mob_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Mob);
      }
      if (top_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Top);
      }
      if (north_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(North);
      }
      if (east_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(East);
      }
      if (south_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(South);
      }
      if (west_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(West);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (terrain_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Terrain);
      }
      if (altTerrain_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(AltTerrain);
      }
      if (terrainModifier_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(TerrainModifier);
      }
      if (pickup_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Pickup);
      }
      if (mob_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(Mob);
      }
      if (top_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(Top);
      }
      if (north_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(North);
      }
      if (east_ != null) {
        output.WriteRawTag(66);
        output.WriteMessage(East);
      }
      if (south_ != null) {
        output.WriteRawTag(74);
        output.WriteMessage(South);
      }
      if (west_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(West);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (terrain_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Terrain);
      }
      if (altTerrain_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(AltTerrain);
      }
      if (terrainModifier_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TerrainModifier);
      }
      if (pickup_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Pickup);
      }
      if (mob_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Mob);
      }
      if (top_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Top);
      }
      if (north_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(North);
      }
      if (east_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(East);
      }
      if (south_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(South);
      }
      if (west_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(West);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Cell other) {
      if (other == null) {
        return;
      }
      if (other.terrain_ != null) {
        if (terrain_ == null) {
          Terrain = new global::STG.Element();
        }
        Terrain.MergeFrom(other.Terrain);
      }
      if (other.altTerrain_ != null) {
        if (altTerrain_ == null) {
          AltTerrain = new global::STG.Element();
        }
        AltTerrain.MergeFrom(other.AltTerrain);
      }
      if (other.terrainModifier_ != null) {
        if (terrainModifier_ == null) {
          TerrainModifier = new global::STG.Element();
        }
        TerrainModifier.MergeFrom(other.TerrainModifier);
      }
      if (other.pickup_ != null) {
        if (pickup_ == null) {
          Pickup = new global::STG.Element();
        }
        Pickup.MergeFrom(other.Pickup);
      }
      if (other.mob_ != null) {
        if (mob_ == null) {
          Mob = new global::STG.Element();
        }
        Mob.MergeFrom(other.Mob);
      }
      if (other.top_ != null) {
        if (top_ == null) {
          Top = new global::STG.Element();
        }
        Top.MergeFrom(other.Top);
      }
      if (other.north_ != null) {
        if (north_ == null) {
          North = new global::STG.Element();
        }
        North.MergeFrom(other.North);
      }
      if (other.east_ != null) {
        if (east_ == null) {
          East = new global::STG.Element();
        }
        East.MergeFrom(other.East);
      }
      if (other.south_ != null) {
        if (south_ == null) {
          South = new global::STG.Element();
        }
        South.MergeFrom(other.South);
      }
      if (other.west_ != null) {
        if (west_ == null) {
          West = new global::STG.Element();
        }
        West.MergeFrom(other.West);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (terrain_ == null) {
              Terrain = new global::STG.Element();
            }
            input.ReadMessage(Terrain);
            break;
          }
          case 18: {
            if (altTerrain_ == null) {
              AltTerrain = new global::STG.Element();
            }
            input.ReadMessage(AltTerrain);
            break;
          }
          case 26: {
            if (terrainModifier_ == null) {
              TerrainModifier = new global::STG.Element();
            }
            input.ReadMessage(TerrainModifier);
            break;
          }
          case 34: {
            if (pickup_ == null) {
              Pickup = new global::STG.Element();
            }
            input.ReadMessage(Pickup);
            break;
          }
          case 42: {
            if (mob_ == null) {
              Mob = new global::STG.Element();
            }
            input.ReadMessage(Mob);
            break;
          }
          case 50: {
            if (top_ == null) {
              Top = new global::STG.Element();
            }
            input.ReadMessage(Top);
            break;
          }
          case 58: {
            if (north_ == null) {
              North = new global::STG.Element();
            }
            input.ReadMessage(North);
            break;
          }
          case 66: {
            if (east_ == null) {
              East = new global::STG.Element();
            }
            input.ReadMessage(East);
            break;
          }
          case 74: {
            if (south_ == null) {
              South = new global::STG.Element();
            }
            input.ReadMessage(South);
            break;
          }
          case 82: {
            if (west_ == null) {
              West = new global::STG.Element();
            }
            input.ReadMessage(West);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (terrain_ == null) {
              Terrain = new global::STG.Element();
            }
            input.ReadMessage(Terrain);
            break;
          }
          case 18: {
            if (altTerrain_ == null) {
              AltTerrain = new global::STG.Element();
            }
            input.ReadMessage(AltTerrain);
            break;
          }
          case 26: {
            if (terrainModifier_ == null) {
              TerrainModifier = new global::STG.Element();
            }
            input.ReadMessage(TerrainModifier);
            break;
          }
          case 34: {
            if (pickup_ == null) {
              Pickup = new global::STG.Element();
            }
            input.ReadMessage(Pickup);
            break;
          }
          case 42: {
            if (mob_ == null) {
              Mob = new global::STG.Element();
            }
            input.ReadMessage(Mob);
            break;
          }
          case 50: {
            if (top_ == null) {
              Top = new global::STG.Element();
            }
            input.ReadMessage(Top);
            break;
          }
          case 58: {
            if (north_ == null) {
              North = new global::STG.Element();
            }
            input.ReadMessage(North);
            break;
          }
          case 66: {
            if (east_ == null) {
              East = new global::STG.Element();
            }
            input.ReadMessage(East);
            break;
          }
          case 74: {
            if (south_ == null) {
              South = new global::STG.Element();
            }
            input.ReadMessage(South);
            break;
          }
          case 82: {
            if (west_ == null) {
              West = new global::STG.Element();
            }
            input.ReadMessage(West);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Element : pb::IMessage<Element>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Element> _parser = new pb::MessageParser<Element>(() => new Element());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Element> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STG.STGProtoReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Element() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Element(Element other) : this() {
      id_ = other.id_;
      rule_ = other.rule_;
      color_ = other.color_;
      channel_ = other.channel_;
      dir_ = other.dir_;
      count_ = other.count_;
      inventory_ = other.inventory_.Clone();
      tags_ = other.tags_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Element Clone() {
      return new Element(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private global::STG.ElemId id_ = global::STG.ElemId.ElementUndefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.ElemId Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "rule" field.</summary>
    public const int RuleFieldNumber = 2;
    private int rule_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rule {
      get { return rule_; }
      set {
        rule_ = value;
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 3;
    private global::STG.Color color_ = global::STG.Color.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Color Color {
      get { return color_; }
      set {
        color_ = value;
      }
    }

    /// <summary>Field number for the "channel" field.</summary>
    public const int ChannelFieldNumber = 4;
    private int channel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Channel {
      get { return channel_; }
      set {
        channel_ = value;
      }
    }

    /// <summary>Field number for the "dir" field.</summary>
    public const int DirFieldNumber = 5;
    private global::STG.Direction dir_ = global::STG.Direction.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Direction Dir {
      get { return dir_; }
      set {
        dir_ = value;
      }
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 6;
    private int count_;
    /// <summary>
    /// Use for inventory counts or piles of items, e.g.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "inventory" field.</summary>
    public const int InventoryFieldNumber = 7;
    private static readonly pb::FieldCodec<global::STG.Element> _repeated_inventory_codec
        = pb::FieldCodec.ForMessage(58, global::STG.Element.Parser);
    private readonly pbc::RepeatedField<global::STG.Element> inventory_ = new pbc::RepeatedField<global::STG.Element>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::STG.Element> Inventory {
      get { return inventory_; }
    }

    /// <summary>Field number for the "tags" field.</summary>
    public const int TagsFieldNumber = 8;
    private static readonly pbc::MapField<string, int>.Codec _map_tags_codec
        = new pbc::MapField<string, int>.Codec(pb::FieldCodec.ForString(10, ""), pb::FieldCodec.ForInt32(16, 0), 66);
    private readonly pbc::MapField<string, int> tags_ = new pbc::MapField<string, int>();
    /// <summary>
    /// is_forced, sliding, etc.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::MapField<string, int> Tags {
      get { return tags_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Element);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Element other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Rule != other.Rule) return false;
      if (Color != other.Color) return false;
      if (Channel != other.Channel) return false;
      if (Dir != other.Dir) return false;
      if (Count != other.Count) return false;
      if(!inventory_.Equals(other.inventory_)) return false;
      if (!Tags.Equals(other.Tags)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != global::STG.ElemId.ElementUndefined) hash ^= Id.GetHashCode();
      if (Rule != 0) hash ^= Rule.GetHashCode();
      if (Color != global::STG.Color.Undefined) hash ^= Color.GetHashCode();
      if (Channel != 0) hash ^= Channel.GetHashCode();
      if (Dir != global::STG.Direction.Undefined) hash ^= Dir.GetHashCode();
      if (Count != 0) hash ^= Count.GetHashCode();
      hash ^= inventory_.GetHashCode();
      hash ^= Tags.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != global::STG.ElemId.ElementUndefined) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Id);
      }
      if (Rule != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rule);
      }
      if (Color != global::STG.Color.Undefined) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Color);
      }
      if (Channel != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Channel);
      }
      if (Dir != global::STG.Direction.Undefined) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Dir);
      }
      if (Count != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Count);
      }
      inventory_.WriteTo(output, _repeated_inventory_codec);
      tags_.WriteTo(output, _map_tags_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != global::STG.ElemId.ElementUndefined) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Id);
      }
      if (Rule != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Rule);
      }
      if (Color != global::STG.Color.Undefined) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Color);
      }
      if (Channel != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Channel);
      }
      if (Dir != global::STG.Direction.Undefined) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Dir);
      }
      if (Count != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Count);
      }
      inventory_.WriteTo(ref output, _repeated_inventory_codec);
      tags_.WriteTo(ref output, _map_tags_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != global::STG.ElemId.ElementUndefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Id);
      }
      if (Rule != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rule);
      }
      if (Color != global::STG.Color.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Color);
      }
      if (Channel != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Channel);
      }
      if (Dir != global::STG.Direction.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Dir);
      }
      if (Count != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Count);
      }
      size += inventory_.CalculateSize(_repeated_inventory_codec);
      size += tags_.CalculateSize(_map_tags_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Element other) {
      if (other == null) {
        return;
      }
      if (other.Id != global::STG.ElemId.ElementUndefined) {
        Id = other.Id;
      }
      if (other.Rule != 0) {
        Rule = other.Rule;
      }
      if (other.Color != global::STG.Color.Undefined) {
        Color = other.Color;
      }
      if (other.Channel != 0) {
        Channel = other.Channel;
      }
      if (other.Dir != global::STG.Direction.Undefined) {
        Dir = other.Dir;
      }
      if (other.Count != 0) {
        Count = other.Count;
      }
      inventory_.Add(other.inventory_);
      tags_.Add(other.tags_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = (global::STG.ElemId) input.ReadEnum();
            break;
          }
          case 16: {
            Rule = input.ReadInt32();
            break;
          }
          case 24: {
            Color = (global::STG.Color) input.ReadEnum();
            break;
          }
          case 32: {
            Channel = input.ReadInt32();
            break;
          }
          case 40: {
            Dir = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 48: {
            Count = input.ReadInt32();
            break;
          }
          case 58: {
            inventory_.AddEntriesFrom(input, _repeated_inventory_codec);
            break;
          }
          case 66: {
            tags_.AddEntriesFrom(input, _map_tags_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = (global::STG.ElemId) input.ReadEnum();
            break;
          }
          case 16: {
            Rule = input.ReadInt32();
            break;
          }
          case 24: {
            Color = (global::STG.Color) input.ReadEnum();
            break;
          }
          case 32: {
            Channel = input.ReadInt32();
            break;
          }
          case 40: {
            Dir = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 48: {
            Count = input.ReadInt32();
            break;
          }
          case 58: {
            inventory_.AddEntriesFrom(ref input, _repeated_inventory_codec);
            break;
          }
          case 66: {
            tags_.AddEntriesFrom(ref input, _map_tags_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Input : pb::IMessage<Input>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Input> _parser = new pb::MessageParser<Input>(() => new Input());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Input> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::STG.STGProtoReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Input() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Input(Input other) : this() {
      primary_ = other.primary_;
      secondary_ = other.secondary_;
      action_ = other.action_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Input Clone() {
      return new Input(this);
    }

    /// <summary>Field number for the "primary" field.</summary>
    public const int PrimaryFieldNumber = 1;
    private global::STG.Direction primary_ = global::STG.Direction.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Direction Primary {
      get { return primary_; }
      set {
        primary_ = value;
      }
    }

    /// <summary>Field number for the "secondary" field.</summary>
    public const int SecondaryFieldNumber = 2;
    private global::STG.Direction secondary_ = global::STG.Direction.Undefined;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::STG.Direction Secondary {
      get { return secondary_; }
      set {
        secondary_ = value;
      }
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 3;
    private int action_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Input);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Input other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Primary != other.Primary) return false;
      if (Secondary != other.Secondary) return false;
      if (Action != other.Action) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Primary != global::STG.Direction.Undefined) hash ^= Primary.GetHashCode();
      if (Secondary != global::STG.Direction.Undefined) hash ^= Secondary.GetHashCode();
      if (Action != 0) hash ^= Action.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Primary != global::STG.Direction.Undefined) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Primary);
      }
      if (Secondary != global::STG.Direction.Undefined) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Secondary);
      }
      if (Action != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Primary != global::STG.Direction.Undefined) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Primary);
      }
      if (Secondary != global::STG.Direction.Undefined) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Secondary);
      }
      if (Action != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Primary != global::STG.Direction.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Primary);
      }
      if (Secondary != global::STG.Direction.Undefined) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Secondary);
      }
      if (Action != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Action);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Input other) {
      if (other == null) {
        return;
      }
      if (other.Primary != global::STG.Direction.Undefined) {
        Primary = other.Primary;
      }
      if (other.Secondary != global::STG.Direction.Undefined) {
        Secondary = other.Secondary;
      }
      if (other.Action != 0) {
        Action = other.Action;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Primary = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 16: {
            Secondary = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 24: {
            Action = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Primary = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 16: {
            Secondary = (global::STG.Direction) input.ReadEnum();
            break;
          }
          case 24: {
            Action = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
